### ISSUE TITLE
Hide plain text PSK? 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/wifi#18]
Do we need the PSK in plain text commented out in wpa_supplicant.conf?

**Comment by emrysr** [comment]
https://github.com/emoncms/wifi/blob/master/wifi.php#L170
`$config .= sprintf("\nnetwork={\n\tssid=\"%s\"\n\t#psk=\"%s\"\n\tpsk=%s\n}\n", $ssid, $network->PSK, $psk);`


I don't think it matters having the psk in plain-text. The built in wpa supplicant command `wpa_passphrase` outputs the plain text password:
```
network={
	ssid="my-wifi-ssid"
	#psk="my-password"
	psk=8fc954a72ef55088f580ed6e5b531b2ba9257a3a9dba31a1a636c74700852efe
}
```
*raspberrypi.org forum: Hiding Wifi Key:*
> the network can be accessed with either the passphrase or the key - obscuring the passphrase and instead exposing the key does not help to secure the network.
- https://www.raspberrypi.org/forums/viewtopic.php?t=76029

**Comment by glynhudson** [comment]
Ok good point. Why do we go to the bother of generating the PSK key when we
could just use the PSK in plain text to connect to a network?
wpa_supplicant.conf can handle plan text PSK's fine.
